#!/usr/bin/env python3
"""
Transcription pipeline: Demucs (stem separation) + MR-MT3 (transcription)
This module handles the actual ML processing.
"""

import os
import sys
import json
import subprocess
import tempfile
import shutil
from pathlib import Path


def separate_stems(audio_path: str, output_dir: str) -> dict:
    """Run Demucs to separate audio into stems"""
    print(f"[Demucs] Separating stems from: {audio_path}", file=sys.stderr)

    subprocess.run([
        'demucs',
        '-n', 'htdemucs',
        '-o', output_dir,
        audio_path
    ], check=True)

    song_name = Path(audio_path).stem
    stems_dir = os.path.join(output_dir, 'htdemucs', song_name)

    return {
        'vocals': os.path.join(stems_dir, 'vocals.wav'),
        'drums': os.path.join(stems_dir, 'drums.wav'),
        'bass': os.path.join(stems_dir, 'bass.wav'),
        'other': os.path.join(stems_dir, 'other.wav'),
    }


def transcribe_with_mt3(audio_path: str, output_dir: str, mt3_dir: str = None) -> str:
    """Run MR-MT3 inference on audio file"""
    print(f"[MR-MT3] Transcribing: {audio_path}", file=sys.stderr)

    if mt3_dir is None:
        mt3_dir = os.environ.get('MT3_DIR', './MR-MT3')

    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)

    # Run MR-MT3 inference
    subprocess.run([
        sys.executable,  # Use same Python interpreter
        'inference.py',
        '--audio_path', audio_path,
        '--output_dir', output_dir,
    ], check=True, cwd=mt3_dir)

    # Find output MIDI file
    for f in os.listdir(output_dir):
        if f.endswith('.mid') or f.endswith('.midi'):
            return os.path.join(output_dir, f)

    raise FileNotFoundError("No MIDI file generated by MR-MT3")


def parse_midi_to_notes(midi_path: str) -> list:
    """Parse MIDI file to note array"""
    import pretty_midi

    print(f"[Parser] Parsing MIDI: {midi_path}", file=sys.stderr)

    midi = pretty_midi.PrettyMIDI(midi_path)
    notes = []

    note_names = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']

    for instrument in midi.instruments:
        # Get instrument name
        if instrument.is_drum:
            inst_name = 'Drums'
        else:
            inst_name = pretty_midi.program_to_instrument_name(instrument.program)

        for note in instrument.notes:
            pitch_name = note_names[note.pitch % 12] + str(note.pitch // 12 - 1)

            notes.append({
                'pitch': pitch_name,
                'midi': note.pitch,
                'startTime': round(note.start, 4),
                'endTime': round(note.end, 4),
                'duration': round(note.end - note.start, 4),
                'velocity': note.velocity,
                'instrument': inst_name,
            })

    # Sort by start time
    notes.sort(key=lambda x: x['startTime'])

    print(f"[Parser] Extracted {len(notes)} notes", file=sys.stderr)
    return notes


def get_audio_duration(audio_path: str) -> float:
    """Get duration of audio file in seconds"""
    import librosa
    duration = librosa.get_duration(path=audio_path)
    return round(duration, 2)


def process_audio(audio_path: str, separate: bool = True, mt3_dir: str = None) -> dict:
    """
    Full pipeline: separate (optional) -> transcribe -> parse

    Args:
        audio_path: Path to input audio file
        separate: Whether to run stem separation first
        mt3_dir: Path to MR-MT3 repository

    Returns:
        Dictionary with notes array and metadata
    """
    with tempfile.TemporaryDirectory() as tmp_dir:
        # Get original audio duration
        duration = get_audio_duration(audio_path)
        print(f"[Pipeline] Audio duration: {duration}s", file=sys.stderr)

        if separate:
            print("[Pipeline] Step 1/3: Separating stems with Demucs...", file=sys.stderr)
            stems = separate_stems(audio_path, tmp_dir)
            # Use 'other' stem (contains melody/piano/guitar)
            # Could also combine bass + other for fuller transcription
            audio_to_transcribe = stems['other']
            stems_info = {k: os.path.basename(v) for k, v in stems.items()}
        else:
            print("[Pipeline] Step 1/3: Skipping stem separation", file=sys.stderr)
            audio_to_transcribe = audio_path
            stems_info = None

        print("[Pipeline] Step 2/3: Transcribing with MR-MT3...", file=sys.stderr)
        midi_dir = os.path.join(tmp_dir, 'midi_output')
        os.makedirs(midi_dir, exist_ok=True)
        midi_path = transcribe_with_mt3(audio_to_transcribe, midi_dir, mt3_dir)

        print("[Pipeline] Step 3/3: Parsing MIDI to notes...", file=sys.stderr)
        notes = parse_midi_to_notes(midi_path)

        # Calculate actual duration from notes if available
        notes_duration = max((n['endTime'] for n in notes), default=0) if notes else 0

        print(f"[Pipeline] Done! Extracted {len(notes)} notes.", file=sys.stderr)

        return {
            'notes': notes,
            'noteCount': len(notes),
            'duration': duration,
            'notesDuration': round(notes_duration, 2),
            'stemsSeparated': separate,
            'stemsInfo': stems_info,
        }


def main():
    """CLI interface for testing"""
    import argparse

    parser = argparse.ArgumentParser(description='Transcribe audio to notes')
    parser.add_argument('audio_path', help='Path to audio file')
    parser.add_argument('--no-separate', action='store_true', help='Skip stem separation')
    parser.add_argument('--mt3-dir', default=None, help='Path to MR-MT3 directory')
    parser.add_argument('--output', '-o', help='Output JSON file (default: stdout)')

    args = parser.parse_args()

    if not os.path.exists(args.audio_path):
        print(f"Error: File not found: {args.audio_path}", file=sys.stderr)
        sys.exit(1)

    result = process_audio(
        args.audio_path,
        separate=not args.no_separate,
        mt3_dir=args.mt3_dir
    )

    output_json = json.dumps(result, indent=2)

    if args.output:
        with open(args.output, 'w') as f:
            f.write(output_json)
        print(f"Output saved to: {args.output}", file=sys.stderr)
    else:
        print(output_json)


if __name__ == '__main__':
    main()
